name: Test_Runner

on: [push]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Wait for database service to be ready on localhost
        run: |
          echo "Waiting for db service to be available on localhost..."
          while ! nc -z localhost 5432; do
            sleep 0.1
          done
          echo "Database service is now ready on localhost!"
      
      - name: Run tests
        run: uv run -m unittest
        env:
          DATABASE_URL: "postgresql://testuser:testpassword@localhost:5432/testdb"